/***************************************************************************
 *   Copyright (c) 2025 FreeCAD Developers                                 *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/

#include "PreCompiled.h"

#ifndef _PreComp_
#include <QBuffer>
#include <QByteArray>
#include <QFile>
#include <QPainter>
#include <QPdfWriter>
#include <QSvgGenerator>
#include <QSvgRenderer>
#include <QPageSize>
#include <QRectF>
#include <QTextStream>
#include <QFont>
#include <QPainterPath>
#include <QVector>
#endif

#include <algorithm>
#include <cmath>
#include <memory>

#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/Placement.h>
#include <Base/Tools.h>
#include <App/GuiApplicationBootstrap.h>

#include "PageRenderer.h"
#include "DrawPage.h"
#include "DrawTemplate.h"
#include "DrawSVGTemplate.h"
#include "DrawParametricTemplate.h"
#include "DrawViewPart.h"
#include "DrawViewAnnotation.h"
#include "LineGenerator.h"
#include "LineGroup.h"
#include "Preferences.h"
#include "Cosmetic.h"
#include "Geometry.h"

#include <GCPnts_TangentialDeflection.hxx>
#include <GeomAdaptor_Curve.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS.hxx>
#include <TopExp_Explorer.hxx>
#include <BRep_Tool.hxx>
#include <Geom_Curve.hxx>
#include <Geom_TrimmedCurve.hxx>
#include <Geom_Line.hxx>
#include <Geom_Circle.hxx>
#include <Geom_Ellipse.hxx>
#include <Geom_BSplineCurve.hxx>
#include <TopoDS_Compound.hxx>
#include <gp_Ax3.hxx>
#include <gp_Dir.hxx>
#include <gp_Pnt.hxx>
#include <gp_Trsf.hxx>
#include <Precision.hxx>
#include <Standard_Failure.hxx>

using namespace TechDraw;

namespace
{
constexpr const char* kPageRendererErrorPrefix = "PageRenderer: ";
constexpr const char* kSvgTitle = "FreeCAD TechDraw Page";
constexpr const char* kSvgDescription = "Generated by FreeCAD TechDraw";
constexpr const char* kSvgVersion = "1.1";
constexpr const char* kSvgGenerator = "FreeCAD TechDraw";

bool ensureGuiApplication() { return App::QtApp::ensureGuiApplication(); }

void scalePenToDevice(QPen& pen, double mmToDevice)
{
    if (pen.style() == Qt::NoPen) {
        return;
    }

    const double widthMM = pen.widthF();
    const double deviceWidth = widthMM * mmToDevice;
    pen.setWidthF(deviceWidth > 0.0 ? deviceWidth : mmToDevice * 0.1);

    QVector<qreal> pattern = pen.dashPattern();
    if (!pattern.isEmpty()) {
        for (auto& value : pattern) {
            value *= mmToDevice;
        }
        pen.setDashPattern(pattern);
    }

    pen.setDashOffset(pen.dashOffset() * mmToDevice);
}
}

//===========================================================================
// PageRenderer
//===========================================================================

PageRenderer::PageRenderer()
    : m_page(nullptr)
    , m_resolution(300.0)  // Default 300 DPI
    , m_templateRenderer(std::make_unique<TemplateRenderer>())
{
}

PageRenderer::PageRenderer(const DrawPage* page)
    : m_page(page)
    , m_resolution(300.0)
    , m_templateRenderer(std::make_unique<TemplateRenderer>())
{
    if (page && page->hasValidTemplate()) {
        auto* template_ = dynamic_cast<const DrawTemplate*>(page->Template.getValue());
        if (template_) {
            m_templateRenderer->setTemplate(template_);
        }
    }
}

PageRenderer::~PageRenderer() = default;

void PageRenderer::setPage(const DrawPage* page)
{
    m_page = page;
    clearError();

    if (page && page->hasValidTemplate()) {
        auto* template_ = dynamic_cast<const DrawTemplate*>(page->Template.getValue());
        if (template_) {
            m_templateRenderer->setTemplate(template_);
        }
    }
}

const DrawPage* PageRenderer::getPage() const
{
    return m_page;
}

void PageRenderer::setResolution(double dpi)
{
    if (dpi > 0.0) {
        m_resolution = dpi;
    }
}

double PageRenderer::getResolution() const
{
    return m_resolution;
}

bool PageRenderer::renderToPDF(const std::string& filePath) const
{
    clearError();

    if (!m_page) {
        setError("No page set for rendering");
        return false;
    }

    if (filePath.empty()) {
        setError("Empty file path provided");
        return false;
    }

    if (!ensureGuiApplication()) {
        setError("Qt GUI application unavailable for PDF rendering");
        return false;
    }

    try {
        double width, height;
        calculatePageBounds(width, height);

        QPdfWriter pdfWriter(QString::fromStdString(filePath));
        pdfWriter.setResolution(static_cast<int>(m_resolution));
        const double mmToPoints = 72.0 / 25.4;
        pdfWriter.setPageSize(
            QPageSize(QSizeF(width * mmToPoints, height * mmToPoints), QPageSize::Point));
        pdfWriter.setPageMargins(QMarginsF(0, 0, 0, 0));

        QPainter painter(&pdfWriter);
        if (!painter.isActive()) {
            setError("Failed to initialize PDF painter");
            return false;
        }

        setupPainter(painter);
        renderTemplate(painter);

        // Phase 2: Render views (including sketches)
        renderViews(painter);

        painter.end();

        Base::Console().message("PageRenderer: PDF exported to %s\n", filePath.c_str());
        return true;
    }
    catch (const std::exception& e) {
        setError(std::string("PDF rendering failed: ") + e.what());
        return false;
    }
}

bool PageRenderer::renderToSVG(const std::string& filePath) const
{
    clearError();

    if (!m_page) {
        setError("No page set for rendering");
        return false;
    }

    if (filePath.empty()) {
        setError("Empty file path provided");
        return false;
    }

    if (!ensureGuiApplication()) {
        setError("Qt GUI application unavailable for SVG rendering");
        return false;
    }

    try {
        std::string svgContent = renderToSVGString();
        if (svgContent.empty()) {
            return false; // Error already set in renderToSVGString
        }

        QFile file(QString::fromStdString(filePath));
        if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
            QString errorString = file.errorString();
            setError(std::string("Failed to open file for writing: ") + filePath +
                    " (" + errorString.toStdString() + ")");
            return false;
        }

        QTextStream stream(&file);
        stream << QString::fromStdString(svgContent);
        file.close();

        Base::Console().message("PageRenderer: SVG exported to %s\n", filePath.c_str());
        return true;
    }
    catch (const std::exception& e) {
        setError(std::string("SVG rendering failed: ") + e.what());
        return false;
    }
}

std::string PageRenderer::renderToSVGString() const
{
    clearError();

    if (!m_page) {
        setError("No page set for rendering");
        return std::string();
    }

    if (!ensureGuiApplication()) {
        setError("Qt GUI application unavailable for SVG rendering");
        return std::string();
    }

    try {
        double width, height;
        calculatePageBounds(width, height);

        QBuffer buffer;
        buffer.open(QIODevice::WriteOnly);

        QSvgGenerator svgGenerator;
        configureSvgGenerator(svgGenerator, &buffer, width, height);

        QPainter painter(&svgGenerator);
        if (!painter.isActive()) {
            setError("Failed to initialize SVG painter");
            return std::string();
        }

        setupPainter(painter);
        renderTemplate(painter);

        // Phase 2: Render views (including sketches)
        renderViews(painter);

        painter.end();

        buffer.close();
        QByteArray data = buffer.data();
        std::string svg(data.constData(), static_cast<std::size_t>(data.size()));

        const std::string defaultTitle = "<title>Qt SVG Document</title>";
        const std::string defaultDescription = "<desc>Generated with Qt</desc>";
        const std::string customTitle = std::string("<title>") + kSvgTitle + "</title>";
        const std::string customDescription =
            std::string("<desc>") + kSvgDescription + "</desc>";

        const auto replaceOnce = [](std::string& text,
                                    const std::string& needle,
                                    const std::string& replacement) {
            const auto pos = text.find(needle);
            if (pos != std::string::npos) {
                text.replace(pos, needle.size(), replacement);
            }
        };

        replaceOnce(svg, defaultTitle, customTitle);
        replaceOnce(svg, defaultDescription, customDescription);

        return svg;
    }
    catch (const std::exception& e) {
        setError(std::string("SVG string rendering failed: ") + e.what());
        return std::string();
    }
}

std::string PageRenderer::renderTemplateToSVG() const
{
    clearError();

    if (!hasValidTemplate()) {
        setError("No valid template available");
        return std::string();
    }

    if (!ensureGuiApplication()) {
        setError("Qt GUI application unavailable for template rendering");
        return std::string();
    }

    try {
        double width, height;
        calculatePageBounds(width, height);

        QBuffer buffer;
        buffer.open(QIODevice::WriteOnly);

        QSvgGenerator svgGenerator;
        configureSvgGenerator(svgGenerator, &buffer, width, height);

        QPainter painter(&svgGenerator);
        if (!painter.isActive()) {
            setError("Failed to initialize template SVG painter");
            return std::string();
        }

        setupPainter(painter);
        renderTemplate(painter);
        painter.end();

        buffer.close();
        const QByteArray data = buffer.data();
        return std::string(data.constData(), static_cast<std::size_t>(data.size()));
    }
    catch (const std::exception& e) {
        setError(std::string("Template SVG rendering failed: ") + e.what());
        return std::string();
    }
}

bool PageRenderer::hasValidTemplate() const
{
    return m_page && m_page->hasValidTemplate() && m_templateRenderer->isValid();
}

std::string PageRenderer::getLastError() const
{
    return m_lastError;
}

bool PageRenderer::hasError() const
{
    return !m_lastError.empty();
}

// Private methods

void PageRenderer::setupPainter(QPainter& painter) const
{
    painter.setRenderHint(QPainter::Antialiasing, true);
    painter.setRenderHint(QPainter::TextAntialiasing, true);
    painter.setRenderHint(QPainter::SmoothPixmapTransform, true);
}

void PageRenderer::renderTemplate(QPainter& painter) const
{
    if (!hasValidTemplate()) {
        return;
    }

    // Phase 1: Basic template rendering
    // This is a stub implementation - template rendering will be improved
    // in subsequent phases when TemplateRenderer is fully implemented

    std::string templateSVG = m_templateRenderer->renderToSVG();
    if (templateSVG.empty()) {
        return;
    }

    QByteArray data(templateSVG.c_str(), static_cast<int>(templateSVG.size()));
    QSvgRenderer svgRenderer(data);
    if (!svgRenderer.isValid()) {
        Base::Console().warning("PageRenderer: Template SVG invalid, skipping render\n");
        return;
    }

    double widthMM = 0.0;
    double heightMM = 0.0;
    calculatePageBounds(widthMM, heightMM);

    painter.save();

    QSizeF viewBox = svgRenderer.viewBoxF().size();
    if (viewBox.isEmpty()) {
        const QSize defaultSize = svgRenderer.defaultSize();
        if (!defaultSize.isEmpty()) {
            viewBox = defaultSize;
        }
        else {
            viewBox = QSizeF(1.0, 1.0);
        }
    }

    const double deviceDpiX = painter.device()->logicalDpiX();
    const double deviceDpiY = painter.device()->logicalDpiY();
    const double mmToDeviceX = deviceDpiX > 0 ? deviceDpiX / 25.4 : 1.0;
    const double mmToDeviceY = deviceDpiY > 0 ? deviceDpiY / 25.4 : 1.0;
    const double targetWidth = widthMM * mmToDeviceX;
    const double targetHeight = heightMM * mmToDeviceY;

    const double scaleX = targetWidth > 0 ? targetWidth / viewBox.width() : 1.0;
    const double scaleY = targetHeight > 0 ? targetHeight / viewBox.height() : 1.0;
    painter.scale(scaleX, scaleY);

    svgRenderer.render(&painter);
    painter.restore();
}

void PageRenderer::calculatePageBounds(double& width, double& height) const
{
    // Default A4 size in mm
    width = 210.0;
    height = 297.0;

    if (m_page && m_page->hasValidTemplate()) {
        try {
            double templateWidth = m_page->getPageWidth();
            double templateHeight = m_page->getPageHeight();

            // Validate dimensions are reasonable (between 1mm and 10000mm)
            if (templateWidth > 0.0 && templateWidth <= 10000.0 &&
                templateHeight > 0.0 && templateHeight <= 10000.0) {
                width = templateWidth;
                height = templateHeight;
            }
            else {
                Base::Console().warning("PageRenderer: Invalid page dimensions (%.2f x %.2f mm), using A4 defaults\n",
                                      templateWidth, templateHeight);
            }
        }
        catch (const Base::Exception& e) {
            // Keep default values if template access fails
            Base::Console().warning("PageRenderer: Failed to get page dimensions (%s), using A4 defaults\n", e.what());
        }
    }
}

void PageRenderer::configureSvgGenerator(QSvgGenerator& generator,
                                         QIODevice* device,
                                         double widthMM,
                                         double heightMM) const
{
    generator.setOutputDevice(device);
    generator.setTitle(QString::fromUtf8(kSvgTitle));
    generator.setDescription(QString::fromUtf8(kSvgDescription));

    const double dpi = m_resolution > 0.0 ? m_resolution : 72.0;
    generator.setResolution(static_cast<int>(dpi));

    const double mmToPixels = dpi / 25.4;
    constexpr double maxPixelDimension = 1000000.0;

    const auto clampDimension = [&](double mmValue) -> int {
        const double sanitizedMM = std::max(1.0, mmValue);
        const double rawPixels = sanitizedMM * mmToPixels;
        if (rawPixels > maxPixelDimension) {
            Base::Console().warning(
                "PageRenderer: Calculated pixel dimension too large (%.0f), capping to %.0f\n",
                rawPixels,
                maxPixelDimension);
        }
        const double clamped = std::min(rawPixels, maxPixelDimension);
        return std::max(1, static_cast<int>(std::lround(clamped)));
    };

    const int pixelWidth = clampDimension(widthMM);
    const int pixelHeight = clampDimension(heightMM);

    generator.setSize(QSize(pixelWidth, pixelHeight));
    generator.setViewBox(QRectF(0.0, 0.0, static_cast<double>(pixelWidth), static_cast<double>(pixelHeight)));
}

void PageRenderer::setError(const std::string& message) const
{
    m_lastError.assign(kPageRendererErrorPrefix);
    m_lastError.append(message);
}

void PageRenderer::renderViews(QPainter& painter) const
{
    if (!m_page) {
        return;
    }
    // Get all views from the page
    std::vector<App::DocumentObject*> views = m_page->Views.getValues();

    for (auto* obj : views) {
        if (!obj) {
            continue;
        }
        if (auto* partView = dynamic_cast<DrawViewPart*>(obj)) {
            renderViewPart(painter, partView);
        }
        else if (auto* annotationView = dynamic_cast<DrawViewAnnotation*>(obj)) {
            renderViewAnnotation(painter, annotationView);
        }
    }
}

void PageRenderer::renderViewPart(QPainter& painter, const DrawViewPart* view) const
{
    if (!view) {
        return;
    }

    try {
        painter.save();

        const double deviceDpiX = painter.device()->logicalDpiX();
        const double deviceDpiY = painter.device()->logicalDpiY();
        const double mmToDeviceX = deviceDpiX > 0.0 ? deviceDpiX / 25.4 : 1.0;
        const double mmToDeviceY = deviceDpiY > 0.0 ? deviceDpiY / 25.4 : 1.0;
        const double mmToDevice = std::min(mmToDeviceX, mmToDeviceY);
        const double pixelsPerMM = mmToDevice; // geometry is already scaled inside DrawViewPart
        const double geometryScale = mmToDevice;

        const double viewX = view->X.getValue();
        const double viewY = view->Y.getValue();

        // Convert TechDraw Y to Qt Y (pageHeight - techDrawY)
        double pageHeight = m_page ? m_page->getPageHeight() : 297.0;
        double qtY = pageHeight - viewY;

        const double offsetX = viewX * mmToDeviceX;
        const double offsetY = qtY * mmToDeviceY;

        const bool writingPdf = dynamic_cast<const QPdfWriter*>(painter.device()) != nullptr;
        if (writingPdf) {
            Base::Console().message(
                "PageRenderer: PDF render view '%s' viewX=%.3f viewY=%.3f offset=(%.3f, %.3f) "
                "pixelsPerMM=%.5f\n",
                view->getNameInDocument(),
                viewX,
                viewY,
                offsetX,
                offsetY,
                mmToDevice);
        }

        const double painterOffsetX = writingPdf ? 0.0 : offsetX;
        const double painterOffsetY = writingPdf ? 0.0 : offsetY;
        const double geometryOffsetX = writingPdf ? offsetX : 0.0;
        const double geometryOffsetY = writingPdf ? offsetY : 0.0;

        if (painterOffsetX != 0.0 || painterOffsetY != 0.0) {
            painter.translate(painterOffsetX, painterOffsetY);
        }

        LineGenerator generator;
        const QColor defaultColor = Preferences::normalColor().asValue<QColor>();

        const BaseGeomPtrVector edges = view->getEdgeGeometry();
        for (std::size_t index = 0; index < edges.size(); ++index) {
            const auto& edge = edges.at(index);
            if (!edge) {
                continue;
            }

            const GeomFormat* geomFormat = view->getGeomFormatBySelection(static_cast<int>(index));
            bool showEdge = true;
            QPen pen;

            if (geomFormat) {
                const LineFormat& format = geomFormat->m_format;
                showEdge = format.getVisible();

                double width = format.getWidth();
                if (!(width > 0.0)) {
                    width = LineGroup::getDefaultWidth("Thick");
                }

                pen = generator.getBestPen(static_cast<size_t>(format.getLineNumber()),
                                            static_cast<Qt::PenStyle>(format.getStyle()),
                                            width);
                pen.setColor(format.getQColor());
            }
            else {
                const bool hidden = !edge->getHlrVisible();
                const bool isIso = edge->getClassOfEdge() == EdgeClass::UVISO;
                const bool isCenterLine = edge->getCosmetic() && edge->source() == SourceType::CENTERLINE;

                double width = LineGroup::getDefaultWidth(
                    isIso ? "Graphic" : (hidden ? "Thin" : "Thick"));

                if (edge->getCosmetic() && edge->source() == SourceType::COSMETICEDGE) {
                    width = LineGroup::getDefaultWidth("Thin");
                }

                const size_t lineNumber = isCenterLine
                                               ? static_cast<size_t>(Preferences::CenterLineStyle())
                                               : (hidden ? static_cast<size_t>(Preferences::HiddenLineStyle()) : 1U);

                pen = generator.getLinePen(lineNumber, width);
                pen.setColor(defaultColor);
            }

            if (!showEdge || pen.style() == Qt::NoPen) {
                continue;
            }

            QPainterPath path;
            bool handled = false;

            if (edge->getGeomType() == GeomType::GENERIC) {
                if (auto generic = std::dynamic_pointer_cast<Generic>(edge)) {
                    if (!generic->points.empty()) {
                        const auto& pts = generic->points;
                        const auto toDevicePoint = [&](const Base::Vector3d& vec) {
                            const double y = vec.y * pixelsPerMM + geometryOffsetY;
                            return QPointF(geometryOffsetX + vec.x * pixelsPerMM, y);
                        };
                        path.moveTo(toDevicePoint(pts.front()));
                        for (std::size_t i = 1; i < pts.size(); ++i) {
                            path.lineTo(toDevicePoint(pts[i]));
                        }
                        handled = true;
                    }
                }
            }
            scalePenToDevice(pen, geometryScale);
            painter.setPen(pen);

            if (handled) {
                painter.drawPath(path);
            }
            else {
                renderEdge(painter,
                           edge->getOCCEdge(),
                           pixelsPerMM,
                           geometryOffsetX,
                           geometryOffsetY,
                           false);
            }
        }

        painter.restore();
    }
    catch (const Base::Exception& e) {
        Base::Console().warning("PageRenderer: Failed to render DrawViewPart: %s\n", e.what());
    }
    catch (const std::exception& e) {
        Base::Console().warning("PageRenderer: Failed to render DrawViewPart: %s\n", e.what());
    }
}

void PageRenderer::renderViewAnnotation(QPainter& painter, const DrawViewAnnotation* view) const
{
    if (!view) {
        return;
    }

    try {
        painter.save();

        const double deviceDpiX = painter.device()->logicalDpiX();
        const double deviceDpiY = painter.device()->logicalDpiY();
        const double mmToDeviceX = deviceDpiX > 0.0 ? deviceDpiX / 25.4 : 1.0;
        const double mmToDeviceY = deviceDpiY > 0.0 ? deviceDpiY / 25.4 : 1.0;

        const double viewX = view->X.getValue();
        const double viewY = view->Y.getValue();

        // Convert TechDraw Y to Qt Y (pageHeight - techDrawY)
        double pageHeight = m_page ? m_page->getPageHeight() : 297.0;
        double qtY = pageHeight - viewY;

        const double offsetX = viewX * mmToDeviceX;
        const double offsetY = qtY * mmToDeviceY;

        const bool writingPdf = dynamic_cast<const QPdfWriter*>(painter.device()) != nullptr;
        if (writingPdf) {
            Base::Console().message(
                "PageRenderer: PDF render annotation '%s' viewX=%.3f viewY=%.3f offset=(%.3f, %.3f)\n",
                view->getNameInDocument(),
                viewX,
                viewY,
                offsetX,
                offsetY);
            painter.translate(offsetX, offsetY);
        }
        else {
            painter.translate(viewX, qtY);
            painter.scale(mmToDeviceX, mmToDeviceY);
        }

        QFont font = painter.font();
        double textSizeMM = view->TextSize.getValue();
        if (!(textSizeMM > 0.0)) {
            textSizeMM = 3.5;
        }
        double fontPointSize = textSizeMM * 2.83465;
        if (!writingPdf) {
            const double deviceDpi = painter.device()->logicalDpiY();
            const double dpiSafe = deviceDpi > 0.0 ? deviceDpi : 72.0;
            fontPointSize = textSizeMM * 72.0 / dpiSafe;
        }
        font.setPointSizeF(fontPointSize);
        const int style = view->TextStyle.getValue();
        font.setBold(style == 1 || style == 3);
        font.setItalic(style == 2 || style == 3);
        painter.setFont(font);

        QColor textColor = view->TextColor.getValue().asValue<QColor>();
        if (!textColor.isValid()) {
            textColor = Qt::black;
        }
        painter.setPen(QPen(textColor));

        const auto& lines = view->Text.getValues();
        if (!lines.empty()) {
            const int lineSpacePercent = std::max(10, static_cast<int>(view->LineSpace.getValue()));
            const double spacingFactor = static_cast<double>(lineSpacePercent) / 100.0;
            const double step = textSizeMM * spacingFactor;

            double y = 0.0;
            for (const auto& line : lines) {
                if (writingPdf) {
                    painter.drawText(QPointF(0.0, y * mmToDeviceY), QString::fromUtf8(line.c_str()));
                }
                else {
                    painter.drawText(QPointF(0.0, y), QString::fromUtf8(line.c_str()));
                }
                y += step;
            }
        }

        painter.restore();
    }
    catch (const Base::Exception& e) {
        Base::Console().warning("PageRenderer: Failed to render annotation: %s\n", e.what());
    }
    catch (const std::exception& e) {
        Base::Console().warning("PageRenderer: Failed to render annotation: %s\n", e.what());
    }
}

void PageRenderer::renderEdge(QPainter& painter, const TopoDS_Edge& edge, double pixelsPerMM,
                              double offsetX, double offsetY, bool invertY) const
{
    try {
        double first, last;
        opencascade::handle<Geom_Curve> curve = BRep_Tool::Curve(edge, first, last);

        if (curve.IsNull()) {
            return;
        }

        // Check curve type for optimized rendering
        if (opencascade::handle<Geom_Line> line = opencascade::handle<Geom_Line>::DownCast(curve)) {
            renderLine(painter, line, first, last, pixelsPerMM, offsetX, offsetY, invertY);
        }
        else if (opencascade::handle<Geom_Circle> circle = opencascade::handle<Geom_Circle>::DownCast(curve)) {
            renderCircle(painter, circle, first, last, pixelsPerMM, offsetX, offsetY, invertY);
        }
        else if (opencascade::handle<Geom_Ellipse> ellipse = opencascade::handle<Geom_Ellipse>::DownCast(curve)) {
            renderEllipse(painter, ellipse, first, last, pixelsPerMM, offsetX, offsetY, invertY);
        }
        else {
            // Generic curve - tessellate for rendering
            renderGenericCurve(painter, curve, first, last, pixelsPerMM, offsetX, offsetY, invertY);
        }
    }
    catch (const Standard_Failure& e) {
        Base::Console().warning("PageRenderer: OCCT error rendering edge: %s\n", e.GetMessageString());
    }
    catch (...) {
        Base::Console().warning("PageRenderer: Unknown error rendering edge\n");
    }
}

void PageRenderer::renderLine(QPainter& painter, const opencascade::handle<Geom_Line>& line,
                              double first, double last, double pixelsPerMM,
                              double offsetX, double offsetY, bool invertY) const
{
    gp_Pnt p1 = line->Value(first);
    gp_Pnt p2 = line->Value(last);

    const double y1 = invertY ? -p1.Y() : p1.Y();
    const double y2 = invertY ? -p2.Y() : p2.Y();
    QPointF pt1(offsetX + p1.X() * pixelsPerMM, offsetY + y1 * pixelsPerMM);
    QPointF pt2(offsetX + p2.X() * pixelsPerMM, offsetY + y2 * pixelsPerMM);

    painter.drawLine(pt1, pt2);
}

void PageRenderer::renderCircle(QPainter& painter, const opencascade::handle<Geom_Circle>& circle,
                                double first, double last, double pixelsPerMM,
                                double offsetX, double offsetY, bool invertY) const
{
    gp_Pnt center = circle->Location();
    double radius = circle->Radius();

    const double cy = invertY ? -center.Y() : center.Y();
    QPointF centerPt(offsetX + center.X() * pixelsPerMM, offsetY + cy * pixelsPerMM);
    double radiusPx = radius * pixelsPerMM;

    // Check if this is a full circle
    const double fullCircle = 2.0 * M_PI;
    if (std::abs((last - first) - fullCircle) < 1e-6) {
        painter.drawEllipse(centerPt, radiusPx, radiusPx);
    }
    else {
        // Arc - tessellate
        renderGenericCurve(painter, circle, first, last, pixelsPerMM, offsetX, offsetY, invertY);
    }
}

void PageRenderer::renderEllipse(QPainter& painter, const opencascade::handle<Geom_Ellipse>& ellipse,
                                 double first, double last, double pixelsPerMM,
                                 double offsetX, double offsetY, bool invertY) const
{
    // Ellipses are more complex - tessellate
    renderGenericCurve(painter, ellipse, first, last, pixelsPerMM, offsetX, offsetY, invertY);
}

void PageRenderer::renderGenericCurve(QPainter& painter,
                                      const opencascade::handle<Geom_Curve>& curve,
                                      double first, double last, double pixelsPerMM,
                                      double offsetX, double offsetY, bool invertY) const
{
    auto toDevice = [&](const gp_Pnt& point) {
        const double y = invertY ? -point.Y() : point.Y();
        return QPointF(offsetX + point.X() * pixelsPerMM,
                       offsetY + y * pixelsPerMM);
    };

    try {
        GeomAdaptor_Curve adaptor(curve, first, last);
        constexpr double angularTol = 0.25 * (M_PI / 180.0);
        const double chordTol = 0.05;
        GCPnts_TangentialDeflection discretizer(
            adaptor, first, last, angularTol, chordTol, 10000, 2);

        if (discretizer.NbPoints() >= 2) {
            QPolygonF polygon;
            polygon.reserve(static_cast<int>(discretizer.NbPoints()));
            for (Standard_Integer index = 1; index <= discretizer.NbPoints(); ++index) {
                polygon << toDevice(discretizer.Value(index));
            }
            painter.drawPolyline(polygon);
            return;
        }
    }
    catch (const Standard_Failure& e) {
        Base::Console().warning("PageRenderer: curve tessellation error: %s\n", e.GetMessageString());
    }
    catch (...) {
        Base::Console().warning("PageRenderer: unknown error tessellating curve\n");
    }

    const int numSegments =
        std::max(12, static_cast<int>(std::ceil(std::abs(last - first) * 180.0 / (5.0 * M_PI))));
    QPolygonF polygon;
    polygon.reserve(numSegments + 1);
    for (int i = 0; i <= numSegments; ++i) {
        const double param = first + (last - first) * static_cast<double>(i) / numSegments;
        gp_Pnt pt = curve->Value(param);
        polygon << toDevice(pt);
    }

    painter.drawPolyline(polygon);
}

//===========================================================================
// TemplateRenderer
//===========================================================================

TemplateRenderer::TemplateRenderer()
    : m_template(nullptr)
{
}

TemplateRenderer::TemplateRenderer(const DrawTemplate* template_)
    : m_template(template_)
{
}

TemplateRenderer::~TemplateRenderer() = default;

void TemplateRenderer::setTemplate(const DrawTemplate* template_)
{
    m_template = template_;
}

const DrawTemplate* TemplateRenderer::getTemplate() const
{
    return m_template;
}

std::string TemplateRenderer::renderToSVG() const
{
    if (!isValid()) {
        return std::string();
    }

    try {
        std::string svgContent = loadTemplateSVG();
        if (svgContent.empty()) {
            return std::string();
        }

        // Process template fields
        return processTemplateFields(svgContent);
    }
    catch (const std::exception& e) {
        Base::Console().error("TemplateRenderer: Failed to render template: %s\n", e.what());
        return std::string();
    }
}

bool TemplateRenderer::isValid() const
{
    return m_template != nullptr;
}

std::string TemplateRenderer::processTemplateFields(const std::string& svgContent) const
{
    // Phase 1: Basic field substitution stub
    // Phase 2+: Implement proper template field processing

    // For now, validate that the content is reasonable SVG
    if (svgContent.empty()) {
        Base::Console().warning("TemplateRenderer: Empty SVG content provided for field processing\n");
        return std::string();
    }

    // Basic validation that this looks like SVG content
    if (svgContent.find("<svg") == std::string::npos) {
        Base::Console().warning("TemplateRenderer: Content does not appear to contain SVG markup\n");
        // Return it anyway in case it's a fragment
    }

    return svgContent;
}

// Private methods

std::string TemplateRenderer::loadTemplateSVG() const
{
    if (!m_template) {
        return std::string();
    }

    // Phase 1: Basic template loading
    // Different template types need different handling

    if (const auto* svgTemplate = dynamic_cast<const DrawSVGTemplate*>(m_template)) {
        auto* mutableTemplate = const_cast<DrawSVGTemplate*>(svgTemplate);

        try {
            const QString processed = mutableTemplate->processTemplate();
            if (!processed.isEmpty()) {
                const QByteArray utf8 = processed.toUtf8();
                return std::string(utf8.constData(), static_cast<std::size_t>(utf8.size()));
            }
        }
        catch (const Base::Exception& e) {
            Base::Console().warning("TemplateRenderer: Failed to process SVG template: %s\n", e.what());
        }
        catch (const std::exception& e) {
            Base::Console().warning("TemplateRenderer: Failed to process SVG template: %s\n", e.what());
        }

        const char* embeddedPath = svgTemplate->PageResult.getValue();
        if (embeddedPath && *embeddedPath) {
            QFile file(QString::fromUtf8(embeddedPath));
            if (file.open(QIODevice::ReadOnly)) {
                const QByteArray data = file.readAll();
                return std::string(data.constData(), static_cast<std::size_t>(data.size()));
            }
            Base::Console().warning("TemplateRenderer: Unable to open embedded template file %s\n", embeddedPath);
        }

        const char* templatePath = svgTemplate->Template.getValue();
        if (templatePath && *templatePath) {
            QFile file(QString::fromUtf8(templatePath));
            if (file.open(QIODevice::ReadOnly)) {
                const QByteArray data = file.readAll();
                return std::string(data.constData(), static_cast<std::size_t>(data.size()));
            }
            Base::Console().warning("TemplateRenderer: Unable to open template source file %s\n", templatePath);
        }

        return std::string();
    }
    else if (dynamic_cast<const DrawParametricTemplate*>(m_template)) {
        Base::Console().warning("TemplateRenderer: Parametric templates are not yet supported for headless export\n");
        return std::string();
    }

    return std::string();
}

std::string TemplateRenderer::substituteFields(const std::string& content) const
{
    // Phase 1: No field substitution yet
    // Phase 2+: Implement template field replacement
    return content;
}
